### ISSUE TITLE
Missing smart terrain links can crash the game

### ISSUE THREAD

**Issue by Decane** [Decane/SRP#101]
Got this while play-testing the SRP:
```
! [LUA][ERROR] Abort(): [sim_board.iterate_point]: Path between 'red_smart_terrain_6_3' and 'mil_smart_terrain_2_10' does not exist for squad with ID '80'.
 
stack traceback:
	_g.script:51: in function 'abort'
	sim_board.script:152: in function 'iterate_point'
	sim_board.script:816: in function 'find_path'
	sim_squad_generic.script:657: in function 'get_next_action'
	sim_squad_generic.script:502: in function 'update'
	se_monster.script:235: in function <se_monster.script:230>
```
A while back, I ran some code to generate [a list of all missing smart terrain links in the game](https://github.com/Decane/SRP/files/3985507/unlinked_smarts_srp.log) and took notes on the ones that were legitimate concerns. There were two, the first of which I now recognize to have been responsible for the crash above:

1. Military Warehouses:

> Paths missing to 'mil_smart_terrain_2_10' ('Hideout in dry woods') are OK for non-mutant squads, since it has 'sim_type = default' (hence is never a power target for non-mutants) and is not a configured faction target in faction_*.ltx. No scripted squads have it as a target either. However, it has neither 'sim_avail = false' nor 'no_mutant = true' specified, so it could become a power target for mutants. If that were to ever happen, the game would probably crash.
> 
> ACTION: Either add link 'Barrier' -> 'Hideout in dry woods' or specify 'no_mutant = true'.

2. Yantar:

> Paths missing to 'yan_smart_terrain_zombi_spawn' ('Pipe exit') are OK for non-mutant squads, since it has 'sim_type = default' (hence is never a power target for non-mutants) and is not a configured faction target in faction_*.ltx. No scripted squads have it as a target either. However, it has neither 'sim_avail = false' nor 'no_mutant = true' specified, so it could become a power target for mutants. If that were to ever happen, the game would probably crash.
> 
> I think the reason this doesn't really ever happen is that the zombified stalker squad that spawns there (yan_squad_zombi_in_sci_base2) immediately leaves it to attack the Scientists' camp via the 'Passage encampment'. However, I believe that if other zombified squads were to ever capture and saturate the squad capacity (2) of the 'Passage encampment', then yan_squad_zombi_in_sci_base2 would be forced to stay at the 'Pipe exit', in which case it could become a power target for mutants and crash the game.
> 
> ACTION: Either add link 'Passage encampment' -> 'Pipe exit' or specify 'no_mutant = true'.

**Comment by Decane** [comment]
Fixed by https://github.com/Decane/SRP/commit/f8fd8b3616f7aa00c959aa43427684bf0551c2b8.

I see now that scenario (1) actually cannot happen in vanilla and is an SRP v1.0.4 regression (probably exacerbated by https://github.com/Decane/SRP/commit/2cc2850f0aa2b81c679fc1dca785a900831508fc) because only camps occupied by a faction that uses the `faction_brain_human` class can become power targets for mutants in vanilla, and the Monolith faction uses `faction_brain_mutant` instead.

In SRP v1.0.4, I changed things so that camps occupied by _any_ enemy faction of the mutants — human faction brain or not — can become a power target for them. Doing this unlocked the 'Hideout in dry woods' as a potential power target for mutants. It can never be one in vanilla. Commit https://github.com/Decane/SRP/commit/f8fd8b3616f7aa00c959aa43427684bf0551c2b8 again blocks the 'Hideout in dry woods' from becoming a power target for mutants.

Conversely, scenario (2) was also possible in vanilla, as far as I can tell - just very unlikely.

**Comment by Decane** [comment]
If anyone encounters the crash cited in https://github.com/Decane/SRP/issues/101#issue-540550584 and does not wish to start a new game (required for https://github.com/Decane/SRP/commit/f8fd8b3616f7aa00c959aa43427684bf0551c2b8 to take effect), an alternative fix is to insert the following code on the blank line beneath `function is_point_avail(point, faction_id)` in gamedata/scripts/sim_board.script:
```
if point:name() == "mil_smart_terrain_2_10" then return false end
```

**Comment by Decane** [comment]
If anyone encounters the crash cited in https://github.com/Decane/SRP/issues/101#issue-540550584 and does not wish to start a new game (required for https://github.com/Decane/SRP/commit/f8fd8b3616f7aa00c959aa43427684bf0551c2b8 to take effect), an alternative fix is to insert the following code on the blank line beneath `function is_point_avail(point, faction_id)` in gamedata/scripts/sim_board.script:
```
if faction_id == "monster" and point:name() == "mil_smart_terrain_2_10" then
	return false
end
```

**Comment by bojan96** [comment]
That fixed the issue, thank you for quick response.
