### ISSUE TITLE
Hold the position quest might still be not competable under unknown conditions

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#103]
Been waiting for an hour now. SRP version is the latest one at the moment. Got the quest before going to Cordon and leaving Clear Sky so that might be the issue making it not completable but I recall it being not completed way before I used a guide.
![ss_Харлам_03-25-20_00-33-42_(marsh)](https://user-images.githubusercontent.com/35204405/77479685-4cd98c80-6e31-11ea-844c-53502a4b9c85.jpg)

Here's the [user_quicksave.sav](https://github.com/Decane/SRP/files/4377801/user_quicksave.zip).

Optionals used:
* Feasible stealth
* Restored Pistol Ironsights Aiming
* Less Frequent Emissions
* No NPC Weapon Tossing Upon Death
* Prefilled Stashes
* Reasonable Machine Gun Lethality
* Reduces Grenade Spam
* Sleeping Bag + No Intro Movies
* User Configuration Patch

**Comment by Decane** [comment]
Looks like you took the task from a Clear Sky squad with ID "8". No such Clear Sky squad exists in your game anymore. (There _is_ now a renegade squad with the same ID, but that's irrelevant to your issue.)

When the Clear Sky squad you took the task from perished, the task should have been failed by `sim_board:remove_squad`. But I found a bug that can prevent this: asking a squad commander for work again _after_ accepting a capture task via dialogue causes `sim_squad_generic:init_squad_task` to erase the tasker's squad's random_tasks table of "capture_smart" tasks, which prevents the loop in `sim_board:remove_squad` from detecting that the task is in progress and failing it. It's a vanilla bug. Will fix.

Meanwhile, you can retroactively fix the issue by adding the following code to function `CCaptureSmartTask:check_task` in task_objects.script, right above the `local global_time = time_global()` statement:

```
	local src_squad = self.board.squads[self.src_obj]

	if not src_squad or src_squad.player_id ~= self.community then
		self.last_check_task = "fail"
	end
```

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/6130813b273f3f26383d7f2e387634238b687c23.

**Note:** This fix prevents the bug from happening, but it will not correct any 'capture' task that has already become incompletable due to the bug - it is not a retroactive fix. For the latter, see https://github.com/Decane/SRP/issues/103#issuecomment-603822124.
