### ISSUE TITLE
NPC more quiet

### ISSUE THREAD

**Issue by mora145** [Decane/SRP#107]
Hi, guys.
I'm currently playing the CoP Anomaly mod.
I've come across some annoying behavior:
In combat, when I hide (They stop seeing me), it happens that the NPCs instantly abandon their position and start walking like zombies towards me. It's annoying, because I can hide just a few seconds and I know that in a few moments I'll have them a few meters away, being easy to eliminate them with a shotgun.
Does anyone know in which script/file, I can create a ramdom time so that the NPCs take some time to get out of their openings to me?

I've been looking all over the Internet for someone to help me change this behavior, and I haven't found anyone to help me. 
Here's the git: https://github.com/mora145/Anomaly-Vanilla-Files

A screenshot: http://prntscr.com/sbo9pd

**PD: Sorry my english.**

**Comment by Decane** [comment]
Please post Anomaly-related questions in a forum frequented by its developers. I am not familiar with Anomaly or its NPC combat logic implementation.
