### ISSUE TITLE
CS Agroprom Mention

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#11]
_Interesing_: If you ask Nimble about goals in the prefinal (third) phase of the Faction War, he'd say that Clear Sky has to capture roads outside of Greeat Swamps:

> Take control over the vantage point overseeing the path that leads to the Cordon. Without it we’re basically cut off from the outside world.

Nothing special, yeah? However, in original game he'd say something like:

> We have to take paths leading to Escape **and Agroprom**.  In fact, we're cut off from the rest of the world without it.

With my small knowledge of languages other than English and Google Translate help, I've managed to see if Agroprom mentioned in other translations.

* **Russian** - mentioned.
* **English** - not mentioned.
* **Polish** - mentioned.
* **Italian** - mentioned.
* **Czech** - mentioned.
* **Hungarian** - mentioned.

(I don't have dialogs_marsh.xml of other languages in my gamedata).

I don't know if it's a bug or unfinished/removed feature, but maybe you can tell this looking at the game code?
Depending on result, to fix this:
* either you'll make a quest on catching an encampment near Railway Bridge,
* or I'll have to remove Agroprom mention from Nimble phrase.

**Comment by Decane** [comment]
The English text in the unmodded game is:

>Take control over the vantage point overseeing the paths that lead to the Cordon **and Agroprom**. Without it we're basically cut off from the outside world.

In the SRP, I changed this to the text you cited, precisely due to the inconsistency between dialog and the actual mission objective. The game code suggests that whilst GSC originally intended the task to involve capturing multiple smart terrains (the task's code name in tm_marsh.ltx is "mar_story_capture_levelchanger**s**"), the objective was deliberately changed to require just the Southern Farmstead for the final product.

**Comment by Decane** [comment]
@SurDno If you remove the Agroprom mention from the Russian text to align it with the SRP's revised English text, I'm happy to include the revised Russian text in the repo.

**Comment by SurDno** [comment]
Sure. 

BTW, in Russian translation, it says 'point**s**', not 'point', overseeing the path**s**, so that's an issue specific to Englsih translation.

Also fixed some voice/text misalignment issues specific to Marsh dialogs and grammar mistakes. Since GitHub does not support XML either, here it on Ya.Disk: https://yadi.sk/d/gFUFhyE7b4p7xw

**Comment by Decane** [comment]
Thanks - your changes (and earlier subtitles fix) are included in commit b603888.
