### ISSUE TITLE
Crash during mugging scene (code in master) (but solved)

### ISSUE THREAD

**Issue by specialtactics** [Decane/SRP#111]
Hi

I was trying to solve the game save corrupt issue after the mugging scene at garbage, and upon using the code in master, the game crashes at the start of the scene.

xray log says the following:

`[error]Arguments     : LUA error: ...\common\stalker clear sky\gamedata\scripts\_g.script:47: Abort(): [xr_logic.pick_section_from_condlist]: NPC 'gar_space_restrictor_fang_pda_cellar': Function 'play_fake_explosion' is not defined in xr_effects.script.
`

Which I guess must be in reference to 

`on_actor_inside = {+gar_story_came_to_ambush_door} sr_idle@unconscious_start_time_1 %=disable_ui =play_fake_explosion%`

Which is different to the latest stable release

`on_actor_inside = {+gar_story_came_to_ambush_door} sr_idle@unconscious_start_time_1 %=disable_ui =run_postprocess(gar_ambush_hit)%`

I just tried to remove the fake explosion thing and see what happens, so essentially change the line to:

``on_actor_inside = {+gar_story_came_to_ambush_door} sr_idle@unconscious_start_time_1 %=disable_ui%``

And it seems like everything works, specifically

- The scene happens normally (including even the flashbang explosion)
- Game no longer crashes when loading a save after the event

Cheers thanks for the work guys!

**Comment by SurDno** [comment]
Not sure if you can migrate from 1.1.2 to 1.1.3 that easily but you may try importing `scripts/xr_effects.script` that contains the function `play_fake_explosion`.

What you did should also work but there will be no trip wire activation during the cutscene.

**Comment by specialtactics** [comment]
Ah I see, no worries. Can probably close in this case.

If 1.1.2 -> 1.1.3 migration works without needing to start over, let me know.
