### ISSUE TITLE
Remove pistol aim zoom altogether

### ISSUE THREAD

**Issue by wolfboyft** [Decane/SRP#113]
And perhaps replace it with a _real_ simulation of focus: _translating the camera forwards_
I wonder if that idea would be doable/agreeable.

**Comment by Decane** [comment]
This would not be appropriate in the core of the SRP (deviates too much from vanilla). I also fail to see how moving the camera forward would be an improvement over the current FOV-based zoom. Finally, I don't believe the engine supports this.

**Comment by wolfboyft** [comment]
Reason having been because humans can't change their FOV.
