### ISSUE TITLE
Centred weapons pose

### ISSUE THREAD

**Issue by wolfboyft** [Decane/SRP#114]
I wonder if the mildly more realistic centred weapons pose could be added, like how it is in Doom. Or if shooting from the hip could be shown lower down? Also note that when NPCs are moving in a shoot-from-the-hip style they always have their eyes above the gun, ie would be seeing in a centred-weapons-pose.

**Comment by Decane** [comment]
Not appropriate in the core of the SRP (deviates too much from vanilla). And I wouldn't be happy to see this in the "Alternative Ballistics" optional feature either.
