### ISSUE TITLE
The Association with the "Widescreen Patch"

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [Decane/SRP#128]
1. Files "map_spots", "map_spots_complex" , "map_spots_find_upgrade" add ends "_16".
2. To adjust the "#include"list in the"map_spots_16"
In "ui_common" you need to choose vanilla "SRP 1.1.3" or "Widescreen Patch", or something in between to make.
![1](https://user-images.githubusercontent.com/38873082/108591111-b00dcf00-73b2-11eb-924c-2e30e0ed1890.JPG)
![2](https://user-images.githubusercontent.com/38873082/108591115-b3a15600-73b2-11eb-9c4c-48ccb0a96852.JPG)
![3](https://user-images.githubusercontent.com/38873082/108591116-b56b1980-73b2-11eb-8242-585c52d8cc8b.JPG)

**Comment by Georgiy-Timoshin** [comment]
Almost 2 years later, I combined SRP with Widescreen Patch. Now Widescreen Patch will only work when the game itself has determined that the monitor is wide (remapping to _16).
[Widescreen.zip](https://github.com/Decane/SRP/files/10419854/Widescreen.zip)

**Comment by Decane** [comment]
Implemented in https://github.com/Decane/SRP/commit/d7257fd4d306129a875d23bd7bc439a80bdff826.
