### ISSUE TITLE
Reduce Grenade Spam feature causing CTD on new game

### ISSUE THREAD

**Issue by joelmeyer1221** [Decane/SRP#129]
I've been able to install any other feature and start a new game with no issues. Whenever I install the grenade spamming feature, whether it is standalone of with everything else, it crashes shortly after I start a new game (it displays "Creating new game" on the load screen for a few seconds then crashes).

I am on Windows 10 - this may be the issue by itself, but I'd find it odd that only the grenade spam feature would cause an issue.

**Comment by SurDno** [comment]
Do you follow the install order? Addons from the second folder should always be installed after those from the first one, not other other way around.

**Comment by joelmeyer1221** [comment]
So - I haven't actually tried to do _all_ of the features I want installed at the same time since switching to v1.1.3, but even installing the grenade spam feature alone causes the crash issue. Is there another feature that needs to be installed for it to work?

**Comment by Decane** [comment]
The Reduced Grenade Spam feature doesn't depend on any other optional feature. I have no problems starting a new game with the current master branch + Reduced Grenade Spam. Are you using any other mods besides the SRP?

One thing you could try is a clean install of SRP v1.1.3. Then, navigate into `Reduced Grenade Spam\gamedata\configs\gameplay\` and copy the first XML file therein over its equivalent default SRP file. Then start a new game. Does it crash? If not, quit the game and repeat these steps for the second XML file, and the third, and so on until you isolate the culprit.

**Comment by joelmeyer1221** [comment]
Fixed now.

I did initially install CS Complete. I had gone through the uninstall instructions packaged with the Complete mod, but apparently that wasn't enough. Did a fresh install of the game - cleared out the entire game folder from my program files - and it is now working. 

Thanks for helping me! Pumped to finally play it!
