### ISSUE TITLE
Sidorovich discount

### ISSUE THREAD

**Issue by IhorBorovskyi** [Decane/SRP#132]
Hello, can you check please Sidorovich discount, after you deliver him locked box (last main quest on Cordon). When you deliver him box, he says that will give you discount. And if trade with him, for example I can see Sunrise suit, and his price is around 6k rubles, but when I add this suit for buying and add some items to sell, price of Sunrise suit will revert to around 10k rubles and will stay forever like that. Same issue with all other items that he sells.

I have GoG version of Clear sky (russian game language), with SRP 1.1.4 WIP (latest build on github) and its was fresh game.
I have installed additional mods from folders: widescreen patch, Alternative Ballistics, Less Frequent Emissions, No Weapon Sway On Strafe, Real Weapon Names, Reasonable Machine Gun Nest Lethality, Reduced Grenade Spam.

And one more little typo in stash on Cordon on Russian language: name of stash is : Кейс за свалкой
and typo is starting in description in first word:
- must be: Расплачусь я с тобой содержимым кейса, что валяется рядом с...
- and how it now: /асплачусь я с тобой содержимым кейса, что валяется рядом с....

it seems that tag was not closed correctly and first letter "P" is missing. Thank you for your work with this project :)

**Comment by Decane** [comment]
Regarding prices seen in the trade window, there is no bug to fix - what you've described is the correct behavior.

6250 is the 'market price' of the Sunrise Suit, and is what you see when you hover your cursor over it - regardless of whether the item is in your inventory or the trader's inventory when you do so. But the market price is not necessarily the selling price a particular trader will demand.

Every vendor has their own 'markup' that is added to the market price. Without a discount, Sid's markup price multiplier for the Sunrise Suit is 2, yielding a final price of 12500. With a discount, the multiplier is 1.7, yielding a final price of 10625. This final price is what you see in the trade window, and is what you must actually pay the vendor to purchase the item.

Regarding the typo - thanks for reporting. @SurDno Another one for your localization fixes if you haven't spotted it already. :)

**Comment by SurDno** [comment]
> @SurDno Another one for your localization fixes if you haven't spotted it already.

I am finally done with SoC and moving on to CS. I expect to finally finish it by August 22nd, 13th birthday of Clear Sky.
