### ISSUE TITLE
Crash due to insufficiently many available smart terrain jobs

### ISSUE THREAD

**Issue by Decane** [Decane/SRP#133]
### Problem scenario:

As reported in [this Reddit thread](https://www.reddit.com/r/stalker/comments/ocwa8h/stalker_clear_sky_fatal_bug_need_help/), the game may crash with an error similar to ...

>smart_terrain.script:457: [se_smart_terrain:update_npc_jobs]: Insufficient smart terrain jobs for NPC '17257' on smart 'mil_smart_terrain_2_1'.

... when all 6 stalker_general_jobs (see gulag_general.script) at mil_smart_terrain_2_1 ('Camp amidst rocks') at the Army Warehouses are already assigned to stalkers when a 7th stalker tries to enter. ([Crash log with extra diagnostics.](https://github.com/Decane/SRP/files/6760004/crash.log))

Since the maximum squad size in CS is 5, the only way this can happen is if a stalker squad is already stationed at the camp when another squad tries to enter. This is made possible by mil_smart_terrain_2_1 having `squad_capacity = 2` in all.spawn, meaning up to 2 squads are permitted to occupy it simultaneously. So, the camp needs enough general jobs for at least 2 * 5 = 10 NPCs. But it only has 6. The fix is to set its `squad_capacity = 1`.

### Could there be other similar cases?

The only way to be sure is to count the jobs at each of the game's 213 smart terrains and check them against the smart terrain's `squad_capacity`. I printed these stats to the console log using the following modified SRP v1.1.3 scripts:

- [gulag_general.script](https://github.com/Decane/SRP/files/6760042/gulag_general.script.txt)
- [smart_terrain.script](https://github.com/Decane/SRP/files/6760043/smart_terrain.script.txt)

After a few manually added notes, [here are the results.](https://github.com/Decane/SRP/files/6760035/srp113.smart.job.counts.log) Searching the log for ` < npc_capacity!` reveals a few false positives we can ignore, but also one genuine (albeit minor) problem I hadn't noticed before: some smart terrains (e.g. gar_smart_terrain_3_8) do not have enough stalker_surge_jobs to accommodate all possible NPCs at the smart terrain. Fortunately, this alone would never crash the game, since emission cover jobs are optional; NPCs will simply retain their general jobs during an emission if there aren't enough emission cover jobs for them.

**Comment by dutch976** [comment]
I'm getting softlocked by a crash shortly after entering Agroprom from the Garbage. It has the same error 
>smart_terrain.script:457: [se_smart_terrain:update_npc_jobs]: Insufficient smart terrain jobs for NPC '39427' on smart 'gar_smart_terrain_6_3'.
but it refers to a smart terrain that I don't think should be having issues according to your notes - though I may just be misunderstanding.
[XRayEngine_error_report_210814-021751.zip](https://github.com/Decane/SRP/files/6986098/XRayEngine_error_report_210814-021751.zip)

**Comment by Decane** [comment]
@dutch976 Thanks for reporting. That NPC is the leader of the 'gar_bandit_brigade' squad at the Flea Market. Apparently, the _precondition_function for his current smart terrain job (the commander job at the Flea Market) is blocking him from being re-assigned that job once another bandit squad, 'gar_bandit_smart_terrain_5_2_squad_2', enters the Flea Market, because `task_manager.is_more_suitable(squad)` is then returning false for his squad. That function is defined as:
```
function is_more_suitable(our_squad)

	local our_smart = our_squad.board.smarts[our_squad.smart_id]

	if our_smart.stayed_squad_quan <= 1 then -- at most one squad on smart
		return true
	end

	if our_squad:get_script_target() == nil then -- we have no scripted target
		return true
	end

	for squad_id, squad in pairs (our_smart.squads) do
		if squad:get_script_target() == nil then
			return false -- we have a scripted target but some other squad on smart doesn't
		end
	end

	return true -- we have a scripted target and so do all other squads on smart
end
```
The function's name is a bit vague, but looking at what it's doing, its apparent purpose in life is to select the 'most suitable' squad leader at a smart terrain for the one and only commander job at the smart terrain from among several possible squads stationed there. (There is always exactly one squad leader per squad, and at most one commander job per smart terrain, so if multiple squads enter a smart terrain, their squad leaders will have to 'compete' for the commander job.)

I can see how this function could also cause crashes on other smart terrains under similar circumstances. And I don't understand why it prioritizes squads that _don't_ have a scripted target over those that _do_ when selecting between squad leaders for a commander job; if anything, it seems like it should be the other way around, since having a smart terrain as a scripted target typically makes a squad bind more tightly to that smart terrain than if they didn't have it as a scripted target.

I'll need to mull over this some more, but to resolve your crash, you can just edit that function to always return true, i.e. make it look like this:
```
function is_more_suitable()
	return true
end
```

**Comment by dutch976** [comment]
that did the trick, thanks

**Comment by Decane** [comment]
- [Fixed crash due to buggy commander job prioritization](https://github.com/Decane/SRP/commit/442954a646c05ed87fee78d15ef99954ceab3ac4)
- [Fixed 'Camp amidst rocks' smart terrain overloading crash](https://github.com/Decane/SRP/commit/4abfa6a89ca23dca4b75f5ab9837c98304b16a79)
