### ISSUE TITLE
Shadows in game

### ISSUE THREAD

**Issue by Mancheen** [Decane/SRP#134]
DX10.1 sun quality - ultra, anti-aliasing mode 4x, alpha dx10.1. The shadows in the game look like this. Or should it be?
![S T A L K E R   Clear Sky Screenshot 2021 07 14 - 19 28 01 15](https://user-images.githubusercontent.com/87438384/125654586-b3c1e1a3-c884-4542-8749-11344478564c.png)

**Comment by Decane** [comment]
I believe it's working as intended. Ultra quality enables 'soft shadows' which are achieved through a jitter effect. I find it ugly, so I use the 'High' quality setting instead. (You can use the `-smap4096` game executable command line switch to further increase shadow quality.)

**Comment by Mancheen** [comment]
Thank you !
