### ISSUE TITLE
Game crashes after Father Valerian approves Military assault

### ISSUE THREAD

**Issue by Tmp341** [Decane/SRP#135]
I got to the point where i need to "Eliminate the military at the elevator". I talked with Khaletskiy and returned to Father Valerian. After his speech ends, when i press "I’ll do what I can." text to exit the window, my game crashes. I don't have anything in log file (it is empty).

SRP v1.1.4

Mods installed:
- Alternative Ballistics
- Improved LuaJIT Library
- Real Weapon Names
- Sleeping Bag
- Transparent Inventory + Smaller Inventory Grids
- User Configuration Patch
- Widescreen Patch

**Comment by Decane** [comment]
Can you upload a save from which to reproduce the crash?

**Comment by Tmp341** [comment]
I was creating an "all mods for SRP weapons/outfits" patch, seems i forgot to remove it before starting the game. Now i went to the Swamps, dropped my fully modded PM, returned back and checked again without my own mod. It is working this time.

Thanks again.
