### ISSUE TITLE
All Upgrades Mod

### ISSUE THREAD

**Issue by Tmp341** [Decane/SRP#136]
You might not like the sound of it, but i was using that mod years ago. Now, I recreated it to work with your SRP. It was working until i saw 2 errors:

- I grabbed a Fort from dead Stalkers near Bus Station. Went to Stalker Base, tried to upgrade but game crashed with an empty log.
- After i questioned Khaletskiy, i returned back to Father Valerian. At the end of conversation, when i almost get next target to assault military near Elevator, my game crashed again with empty log. 

What might be the cause of these?

**Comment by Decane** [comment]
I'm afraid I have no idea. This is not an appropriate forum to request general modding support.
