### ISSUE TITLE
No AKM-74 in beginning of the game

### ISSUE THREAD

**Issue by mataski** [Decane/SRP#139]
The patches v1.5.09 and v1.5.10 has AKM-74 as starting weapon, but SRP rerolls the setting to v1.5.8 where there was no AKS-74, only shotgun+pistol.

Without SRP: https://youtu.be/XMx7QCGaVXQ?t=138 
With SRP: https://youtu.be/PQNAuiDR8u4?t=1694

Why is that? SRP requires v1.5.10 patch to play.

**Comment by Decane** [comment]
The starting AK is a cheat that perverts starting gear progression and contradicts Scar's dialogue with Suslov. So, it's not coming back.
