### ISSUE TITLE
Shotgun bug

### ISSUE THREAD

**Issue by litvyakov1488** [Decane/SRP#14]
Hey. Found a bug with SPAS-12 shotgun. Whenever I try to change ammo type ("Y" key by default) it doesn't actually change it, instead it shows incomplete reload animation and that's it. However, if you unload a shotgun via invertory and press Y key it changes ammo. Here's my savegame where bug occured. I use the latest "gamedata" no optional mods (just widescreen patch and shaders).
[shotgun_bug_save.zip](https://github.com/Decane/SRP/files/1887287/shotgun_bug_save.zip)

**Comment by SurDno** [comment]
That's related to the fact that SPAS can use different ammo types together. That's an engine bug, nothing Decane can do about it other than removing that ammo feature. I think it should happen with RG-6 too.
