### ISSUE TITLE
 Error at the Hospital location.

### ISSUE THREAD

**Issue by Castlesoap** [Decane/SRP#140]
```
! Cannot find saved game :>Corpse with ID 34049 does not have info. Adding it to release table.
! Cannot find saved game :>Added corpse with ID 34049 and death_time 788 to release table.
! Cannot find saved game :>new_corpse_num 76 body_target_count 15
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : raii_guard::~raii_guard
[error] File          : C:\projects\xray-16\src\xrScriptEngine\script_engine.cpp
[error] Line          : 568
[error] Description   : .... clear sky\gamedata\scripts\release_body_manager.script:84: 'for' limit must be a number
```

I think the limit was more than 75. The game could not find a suitable npc to delete

Also, I do not recommend deleting in the for loop i = 1, release_count do
**sim: release (alife_object (npc_id), true)**
There will definitely be problems!
Better to create a new table and use table.insert to insert the value into the array

And already in a new cycle, ising **sim: release (alife_object (npc_id), true)**  delete

**Comment by Decane** [comment]
Please upload a save file (.sav) from which to reproduce the crash.

>release_body_manager.script:84: 'for' limit must be a number

Have you modified release_body_manager.script? I can't see how the above error could happen with the unmodified SRP script. The limit it's complaining about not being a number is `release_count`, which is defined on line 82 as follows:
```
release_count = rel_corpse_num >= overflow_count and overflow_count or rel_corpse_num
```
As both `rel_corpse_num` and `overflow_count` are numbers, `release_count` must also evaluate to a number.

>I do not recommend deleting in the for loop

Why? There should be nothing unsafe about this code:
```
line 84: for i = 1, release_count do
line 85:	local npc_id = rel_table[1].id
line 86:	sim:release(sim:object(npc_id), true)
line 87:	table_remove(rel_table, 1)
line 88: end
```
The statement on line 87 deletes the _**first**_ element of the table in every loop iteration and shifts all remaining elements of the table down by one. By the time the next iteration starts, another element is at index 1 again. Per line 82, `release_count` can never exceed the number of elements in the table, so there can never be an attempt to delete something that isn't there.

**Comment by Castlesoap** [comment]
I figured it out. Received the same departure.

```
	if new_corpse_num > body_target_count then													-- if the number of corpses in the release table now exceeds body_target_count then
		corpse_time = 3600																		-- attempt to release the furthest-away-from-player corpses in the release table
		corpse_target = body_target_count
		**try_to_release**(npc)
		if #rel_table > body_max_count then														-- if the number of corpses in the release table *then* exceeds body_max_count then
			corpse_time = 6																		-- force the release of the furthest-away-from-player corpses in the release table
			corpse_target = body_max_count
			**try_to_release**(npc)
		end
	end
```

This code will cause a crash

This can be seen from the log

! Cannot find saved game :>Corpse with ID 31751 does not have info. Adding it to release table.
! Cannot find saved game :>Added corpse with ID 31751 and death_time 556 to release table.
! Cannot find saved game :>new_corpse_num 76 body_target_count 15
! Cannot find saved game :>try_to_release1: kat_hosp_z3_floor2_enemy_431751 moving_dead_body5
! Cannot find saved game :>try_to_release2: kat_hosp_z3_floor2_enemy_431751 moving_dead_body6
 
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : raii_guard::~raii_guard
[error] File          : C:\projects\xray-16\src\xrScriptEngine\script_engine.cpp
[error] Line          : 568
[error] Description   : .... clear sky\gamedata\scripts\release_body_manager.script:84: 'for' limit must be a number

since **try_to_release** fires 2 times

Alas, I have modified all_spawn
i have using oxr!
yes I uncommented the logs to understand the reason for the other error **error handler is invoked**
it turned out to be death_manger's fault
I'll try to test it again as the crash is stable

**Comment by Castlesoap** [comment]
Clearing the alarm! I screwed it up! I am so sorry! But on the other hand, thanks to my oversight, the **pure virtual function call** and **error handler is invoked** errors is no longer in oxr!

Need to add this code in death_manager.script in function keep_item

```
	local active_item = npc:active_item()
	if active_item and active_item:id() == item_id then
		dbglog("keep_item:active item=[%s],id=[%s]", section, item_id)
		return
	end
    if item:attachable_item_enabled() then
		dbglog("death[%s] attach_item %s",npc:name(),item:name())
		return
    end
```
