### ISSUE TITLE
Dark Valley behaves like a swamp

### ISSUE THREAD

**Issue by Atryx10** [Decane/SRP#145]
Every now and then you lose the ability to run and jump in the Dark Valley as if you're in the water sections of the Great Swamps. This has happened between the moving Fire ball inside the building, and the swampy area of the Dark Valley, as well as at the fire anomaly by the Cordon passage where you're supposed to go collect an 8x scope from a corpse in one of the "How can I help you?" quests from freedom members.

**Comment by Decane** [comment]
Reduced mobility in bodies of water and thermal anomaly fields is intended.

**Comment by Decane** [comment]
Reduced mobility in bodies of water and thermal anomaly fields is intentional.

**Comment by Atryx10** [comment]
The area between the building and the water in the Dark Valley that I'm referring to is some plain hills and with rocks and bushes. But good to know that reduced mobility in Thermal is intentional!
