### ISSUE TITLE
Mutant parts

### ISSUE THREAD

**Issue by vertebralis** [Decane/SRP#148]
I suppose that mutant parts should be restored or their inventories removed entirely. Their empty inventory like screaming that mutant parts were cut in a rush. There is no purpose of looting dead mutants and opening their's inventories because the're always empty.

**Comment by Decane** [comment]
- Mutant inventories can be used for item disposal.
- Restoration of mutant parts would be pointless (beyond mere trophy-gathering) without also adding support for trading them, which would require arbitrary judgment calls to decide price balancing to fit with the vanilla economy. No thanks.
