### ISSUE TITLE
Won't start in Win10 64-bit

### ISSUE THREAD

**Issue by Corrine-Alastor** [Decane/SRP#16]
I installed v1.1.2 with the widescreen patch, float32 SSAO performance patch, LUAJIT patch, real gun names, reduced grenade spam and the DX10 patch. Nothing else, this is a fresh install aside from your work. I could reach the main menu without your patches, but after installing, I can see one or 2 windows and the rest is just black for about 10 to 15 seconds, then it just closes.

**Comment by Corrine-Alastor** [comment]
Deleting/uninstalling the DX10 patch has fixed it. May want to include this in your installation notes or something.

**Comment by Decane** [comment]
>May want to include this in your installation notes or something.

SRP v1.1.2 - Optional Features.txt:

>====================================================
DX10 Patch
====================================================
>
>
>Allegedly prevents crashes related to the DX10/10.1 renderer without necessitating the removal of 'Update for Microsoft Windows (KB2670838)'.
>
>**Install only if playing in DX10/10.1 mode makes your game crash.**
