### ISSUE TITLE
Engine error when checking if the weapon is set to increase the magnification of sights

### ISSUE THREAD

**Issue by Mancheen** [Decane/SRP#160]
The error remained from the release of the game, perhaps I found a solution to this error, but only I do not know how to edit the game engine. Perhaps a knowledgeable person can fix this error. In CoP zoom_factor is read by the engine when loading the weapon, in CS - no

[xrGame\Weapon.cpp]
BOOL CWeapon::net_Spawn		(CSE_Abstract* DC)
	…
	m_fRTZoomFactor		= m_zoom_params.m_fScopeZoomFactor;	-- _only COP_
	…
	iAmmoElapsed		= E->a_elapsed;
	m_flagsAddOnState	= E->m_addon_flags.get();
	m_ammoType		= E->ammo_type;
	…

**Comment by SurDno** [comment]
Any engine fixes are out of scope for SRP.

**Comment by Decane** [comment]
I recommend OpenXRay for engine fixes. To my understanding, it's [compatible with CS](https://github.com/OpenXRay/xray-16#supported-games) these days. And it [should work with SRP v1.1.4](https://github.com/OpenXRay/xray-16/issues/768#issuecomment-1264627622).
