### ISSUE TITLE
Stalkers from Flea Market not heading to capture

### ISSUE THREAD

**Issue by vlad54rus** [Decane/SRP#165]
I've accepted a task to capture the 'Shore of small swamp' but stalkers continue to sit on the Flea Market like nothing is happening. They only start moving when they're offline.
SRP from the latest commit + Alternative Ballistics, Real Weapon Names and Sleeping Bag
[savedgames.zip](https://github.com/Decane/SRP/files/14874016/savedgames.zip)

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/dbf6a4bf954ef2de1861ec46eb0eb5aed3b3a5cc.
