### ISSUE TITLE
Game Crashing Whenever Loading a Save

### ISSUE THREAD

**Issue by whoisdenke** [Decane/SRP#167]
Installed SRP 1.1.5 first, installed these optionals:
- No Enemy Map Spots
- Alternative Ballistics
- Improved LuaJIT Libs
- Move Faster Through Water
- Real Weapon Names
- Reasonable Machine Gun Nest Lethality
- Reduced Grenade Spam
- Show Only Ally Map Spots
- Sleeping Bag + No Intro Movies
- Smaller Crosshair
- Smaller Player Icon
- Transparent Inventory + Smaller Inv Grids
- User Config Patch

Then, installed AtmosFear 1.3, Absolute Structures/Nature.

Game runs fine when starting new save and creates new saves fine, however if needing to reload a save, or if relaunching and attempting to load save, game crashes at "Synch" portion. Log says this:
```
FATAL ERROR
 
[error]Expression    : fatal error
[error]Function      : CScriptEngine::lua_error
[error]File          : E:\priquel\sources\engine\xrServerEntities\script_engine.cpp
[error]Line          : 180
[error]Description   : <no expression>
[error]Arguments     : LUA error: xr_logic.script:485: attempt to get length of local 'condlist' (a nil value)
 
lua stack:
  [23|-1] (no value):  
  [22|-2] (string):  `attempt to get length of local 'condlist' (a nil value)'
  [21|-3] (nil):  nil
  [20|-4] (nil):  nil
  [19|-5] (nil):  nil
  [18|-6] (nil):  nil
  [17|-7] (nil):  nil
  [16|-8] (nil):  nil
  [15|-9] (nil):  nil
  [14|-10] (nil):  nil
  [13|-11] (nil):  nil
  [12|-12] (nil):  nil
  [11|-13] (nil):  nil
  [10|-14] (nil):  nil
  [ 9|-15] (nil):  nil
  [ 8|-16] (nil):  nil
  [ 7|-17] (nil):  nil
  [ 6|-18] (nil):  nil
  [ 5|-19] (number):  1
  [ 4|-20] (nil):  nil
  [ 3|-21] (nil):  nil
  [ 2|-22] (userdata):  userdata (00733648)
  [ 1|-23] (userdata):  userdata (00733648)
 
 

stack trace: 
```

Verified that xr_logic.script actually has things at line 485, and while I am no coder, I could see no glaring issues or typos in the related lines/branches. SRP is the only mod so far that directly changes that specific file, and I'm not really finding any other problems in other places.

**Comment by whoisdenke** [comment]
Disregard, figured it out.

After clean-wiping all my Stalker files and trying with 1.1.4 SRP, issue was the same. Installed and tested everything individually, and it was actually AtmosFear v1.3 causing the issue, even on a brand new save. Once removed, game was completely fine(at least so far).

**Comment by Decane** [comment]
Duplicates https://github.com/Decane/SRP/issues/158. There is a fix in https://github.com/Decane/SRP/issues/158#issuecomment-2146127921.
