### ISSUE TITLE
new game or loading crashes my game

### ISSUE THREAD

**Issue by space2ninja101** [Decane/SRP#169]
Expression    : fatal error
Function      : CScriptEngine::lua_error
File          : E:\priquel\sources\engine\xrServerEntities\script_engine.cpp
Line          : 180
Description   : <no expression>
Arguments     : LUA error: ...k.e.r. clear sky\gamedata\scripts\sound_theme.script:33: attempt to call global 'parse_names_to_hash' (a nil value)

i cant apply the fix because the _g.script file is modified by srp

**Comment by Decane** [comment]
You've installed the SRP incorrectly and/or have mixed it with other mods incorrectly.
