### ISSUE TITLE
''Sleeping Bag'' optional addon localization

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#19]
Thanks to olegj5, the SRP itself has been translated to Russian for half a year already, but sleeping bag optional addon has almost been not. It has a proper item name and description, but UI is still English. It would be nice if you add translation for that four words in sleeping bag interface.
![image](https://user-images.githubusercontent.com/35204405/46906099-c8c66a00-cf06-11e8-9fe1-64847f7b734d.png)
The translation for them is:

> Safety: — Безопасность:

> Duration: — Продолжительность:

> Sleep — Спать

> Cancel — Отмена

Thank you.

**Comment by Decane** [comment]
Implemented in 0c2b48a.

**Comment by SurDno** [comment]
Very fast. Thank you again.

**Comment by SurDno** [comment]
Tested and found out that 'h' in duration should also be changed to 'ч' in Russian translation. Sorry, totally forgot about it.

**Comment by Decane** [comment]
>Tested and found out that 'h' in duration should also be changed to 'ч' in Russian translation. Sorry, totally forgot about it.

I missed that too, thanks. Added in 4a078f4.
