### ISSUE TITLE
Yoga using wrong audio after completion of his quests

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#25]
When Yoga gives you a shoutout that first and second 'checking' quests are complete, he uses his clear voice phrases for some reason, not muffled 'PDA' versions.

In order to fix this, you have to play '**gar_bandit_leader_kill_digger_traitor_done_a_pda.ogg**', '**gar_bandit_leader_kill_digger_traitor_done_b_pda.ogg**' and '**gar_bandit_leader_kill_smuggler_done_pda.ogg**' instead of '**gar_bandit_leader_kill_digger_traitor_done_a.ogg**', '**gar_bandit_leader_kill_digger_traitor_done_bogg**' and '**gar_bandit_leader_kill_smuggler_done.ogg**' respectively.

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/a4e5f513c87054973684da932b2664079157bdf1#diff-051af66cc444a8708698e19d967506e490a8eead837498cc798f921f260598f8.
