### ISSUE TITLE
No quest on capturing flea market

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#30]
When #29 became too frustrating for me, I tried to capture it like I previously did in clear Clear Sky (pun not intended). But unlike vanilla game, even when there are two bandit squads near the hill near flea market, for some reason, none of them gives you a quest on capturing the point. Here's the save that reproduces it: https://yadi.sk/d/Pqm_YLB6eAFabQ

**Comment by Decane** [comment]
The Flea Market isn't captured by anyone in your save (the stalkers there have actually left it and are moving towards the 'Far outpost'). Hence, no task available to capture it.
