### ISSUE TITLE
Jobs to rescue brother Wolf and the the beginner fail if on stage to accompany them to the village, to retreat to a certain distance

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#39]
Jobs to rescue brother Wolf and the the beginner fail if on stage to accompany them to the village, to retreat to a certain distance. But it's not quite right, because we have already saved them, and if no one killed them on the way, then why does it completely fail?

**Comment by Decane** [comment]
For better or worse, this is working as intended. GSC wrote the following code to make the NPC die if the player strays further than 100m from the NPC while escorting him back to the rookie village:
```
on_actor_dist_ge_nvis = 100 | walker@death %+esc_stalker_novice_fail =kill_npc%
```
There is no ambiguity about whether or not this was intentional.
