### ISSUE TITLE
After the escape of Khaletskiy from the base of stalkers, Father Valerian tells that he killed 2 guards, but in fact, it's not so

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#40]
After the escape of Khaletskiy from the base of stalkers, Father Valerian tells that he killed 2 guards, but in fact, it's not so. What can you do about it?

**Comment by Decane** [comment]
There is no in-game evidence contradicting Valerian's testimony, so I can't accept this as a bug. We could create evidence to explicitly _support_ his testimony e.g. by spawning two permanent corpses next to Khaletskiy's cell after the game has de-spawned him, but I don't think changes like that are appropriate for the SRP.

**Comment by SurDno** [comment]
I’d say it’s more of an oversight.
