### ISSUE TITLE
if the player takes the suit from another inventory the artifacts from the already dressed costume also fall in inventory

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#41]
If you take from the drawer or the inventory of a corpse, suit to player inventory, the artifacts of the slots already wearing a suit is placed in your inventory (possibly a engine bug\glitch)

**Comment by Decane** [comment]
This is a regression introduced in 90f270a by:

>Fixed the player's character model reverting back to the default rookie jacket model upon picking up another suit or loading a savegame / changing maps.

I'm not sure I can fix this one - I can't find an equivalent of the engine function ToBelt() listed in lua_help.script to enable programmatically attaching artifacts to the belt.

**Comment by Decane** [comment]
I can't fix this, so in eb4bc48 I've reverted the hack used to fix the character model reverting to the default rookie jacket model upon picking up a new suit. Curiously, the same hack does not result in unequipped artifacts when applied to fix the same bug on loading a savegame / changing maps, so we can retain that fix.
