### ISSUE TITLE
bug with wrong saving of cartridge type in shotgun after saving and loading.

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#51]
bug with wrong saving of cartridge type in shotgun after saving and loading. For example when being charged type 2 cartridge in the chamber, after saving\loading remains only the last type replaces the previous one.

**Comment by SurDno** [comment]
OGSR decided to remove the feature altogether because it caused too many problems, by the way.

**Comment by Decane** [comment]
Bug confirmed. Steps taken to reproduce:

1. Load 4 buckshot shells and then 4 slugs into an empty shotgun that can take 8 rounds, from an initial inventory of:
   - 8 buckshot shells
   - 10 slugs
2. Inventory now contains 4 buckshot shells, 6 slugs. Save/reload.
5. Unload shotgun.
6. Inventory now contains 4 buckshot shells, 10 slugs. 4 buckshot shells have disappeared into the ether!

**Comment by SurDno** [comment]
OGSR engine just removed the whole multi ammo type support altogether because it produced too many bugs. Not sure if it would be simple to fix even with engine changes.
