### ISSUE TITLE
Corpses may still be rendered as squad commanders on PDA

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#53]
![20181103222043_1](https://user-images.githubusercontent.com/35204405/48676382-3d7c6c00-eb77-11e8-8e32-7a7561c302b4.jpg)

This issue does not persist when save/load, so I don't know if a savefile can help, but still [here it is](https://yadi.sk/d/q-yyx9QQ68sp8g).

**Comment by Decane** [comment]
This regression was fixed in 67a936d a couple of weeks ago.
