### ISSUE TITLE
NPC trader sitting on Red Forest Cave chair may be a little bit off

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#60]
![image](https://user-images.githubusercontent.com/35204405/48680349-b1386c00-ebab-11e8-94bb-84c3349e1b9d.png)

[Save](https://yadi.sk/d/hy1HqvAMxQBVqw).

**Comment by Decane** [comment]
Per the readme entry from a recent commit:

>• The trader in the Red Forest mine often levitates in the air beside his stool in a sitting position rather than being positioned on the stool itself. **This is an SRP v1.0.4 regression.**

This regression is necessary to prevent a crash in the Red Forest if the trader in the mine strays from his spot at the desk:

>[error]Description : any vertex in patrol path [red_smart_terrain_3_2_patrol_1_walk] is inaccessible for object [sim_default_duty_221783]

The code change responsible for the regression is the commenting out of the Red Forest mine trader's 'out restrictor' in gamedata\configs\scripts\red_forest\red_smart_terrain_3_2_logic.ltx:
```
;out_restr = red_smart_terrain_3_2_mechanic_restr
```
The out restrictor is what seems to keep him correctly positioned on the stool. Ideally, the engine would not trigger a crash when an NPC is displaced from their out restrictor, but until that's the case, preventing the crash via the NPC's logic script is more important to me than correctly positioning the trader on the stool.
