### ISSUE TITLE
Yar's quest behaves incorrectly

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#7]
When Yar gives you the quest, he says, that he needs PDA before sunrise. However, the quest only gets failed if you don't **take PDA** until dawn, while you can carry it to Yar anywhen.

**Comment by Decane** [comment]
It's also possible to cheat the time limit by exiting the Dark Valley shortly before 6:00 and re-entering after 23:00. But I won't fix that - it's a limitation of S.T.A.L.K.E.R.'s object binder system, which governs the space restrictor to which the quest logic is bound.

**Comment by Decane** [comment]
Fixed by SurDno in https://github.com/Decane/SRP/pull/99.
