### ISSUE TITLE
Bandits do not take Garbage level changers

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#71]
Unlike vanilla, in the SRP bandits do not even try to capture level changers to Agroprom, Dark Valley and Army Warehouses.

**Comment by Decane** [comment]
Bandits will attempt to capture those level changers only if their faction brain prioritizes them as strategic points. Whether that happens depends on their prioritization relative to other camps and the availability of bandit squads to move to them. Both of these can vary substantially from one play-through to the next depending on e.g. which surrounding camps are occupied by which faction, among other factors.

Also, smart terrain prioritization is intentionally altered in the SRP per my reply to https://github.com/Decane/SRP/issues/70. This may or may not have reduced the bandits' willingness to become cannon fodder for those level changers relative to vanilla. However, there is nothing in the SRP that outright prevents them from attempting to capture those level changers.
