### ISSUE TITLE
Animation missing when switching grenades.

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#8]
When you swap between weapons, it first plays previous weapon hiding animation, and then plays next weapon getting out animation.
However, when you switch grenade type with a grenade in your hand ('Y' by default), the game just abruptly cuts previous animation instead of a making a smooth transition.

**Comment by SurDno** [comment]
„Engine bug“ and „Need help” labels, I guess?

**Comment by Decane** [comment]
I don't think the engine supports animated grenade type switching.
