### ISSUE TITLE
Help with install of patch

### ISSUE THREAD

**Issue by Debweb86** [Decane/SRP#86]
Hi, everybody.Prompt downloaded and there three folders .. just throw them in the game folder or the contents of the folder ?
gamedata
Optional Features
Widescreen Patch

**Comment by Decane** [comment]
There are detailed installation instructions in the file named "SRP v1.1.3 - Readme.txt" at the root of this GitHub repository. That file should also exist in the archive you downloaded. Short version: paste the 'gamedata' folder into your game's installation directory. For more info, please read the readme.
