### ISSUE TITLE
Map marker for "PDA with secret information" at wrong spot

### ISSUE THREAD

**Issue by eqagunn** [Decane/SRP#93]
Map marker for "PDA with secret information" is placed at Hidden Camp (Swamps) instead of Encampment in Hills (Garbage).

![ss_matz-laptop_07-01-19_06-09-32_(garbage)](https://user-images.githubusercontent.com/25494031/60527715-b08fb880-9cea-11e9-991a-2cad9aa44395.jpg)

**Comment by Decane** [comment]
Is this with SRP v1.1.2 or v1.1.3? It should be fixed in the latter, since commit https://github.com/Decane/SRP/commit/75f161e30b87dffbecbf35bd7525e6a32c84c0e4.

**Comment by eqagunn** [comment]
This is with v1.1.3-rc2.

**Comment by Decane** [comment]
OK - v1.1.3 RC2 precedes that commit, so it doesn't contain the fix.
